module.exports = Object.freeze({
  PLAYER_RADIUS: 20,
  PLAYER_MAX_HP: 100,
  PLAYER_SPEED: 400,
  PLAYER_FIRE_COOLDOWN: 0.25,

  BULLET_RADIUS: 3,
  BULLET_SPEED: 800,
  BULLET_DAMAGE: 10,

  SCORE_BULLET_HIT: 20,
  SCORE_PER_SECOND: 1,

  MAP_SIZE: 3000,
  MSG_TYPES: {
    CREATE_GAME: 'create_game',
    PLAYER_LIST: 'player_list',
    ASK_FOR_GAME_LIST: 'ask_for_game_list',
    GAME_LIST: 'game_list',
    JOIN_GAME: 'join_game',
    START_GAME: 'start_game',
    GAME_UPDATE: 'update',
    DRAW_REQUEST: 'draw_request',
    PLAY_REQUEST: 'play_request',
    DISCARD_REQUEST: 'discard_request',
    INPUT: 'input',
    GAME_OVER: 'dead',
    GAME_OVER: 'dead',
    CHAT: 'chatMessage',
    LEAVE_GAME: 'leave_game',
    JOIN_GAME_FAILED: 'join_game_failed',
  },
  GAME_STATES: {
    DRAW: 'draw',
    PLAY: 'play',
    DISCARD: 'discard',
    END: 'end',
  },
  GAME_CONFIG: {
    HAND_SIZE: 7,
    MAX_SPECIES: 10,
    MIN_SPECIES: 2,
    SPECIES_PER_PLAYER: 2,
    CARDS_PER_SPECIES: 8,
    HAND_SIZE_PLAY: 9,
  },
});
